// AUTH ACTION TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADED_JWT = 'USER_LOADED_JWT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const UPDATE_ME = 'UPDATE_ME';
export const UPDATE_ERROR = 'UPDATE_ERROR';

// CODE QUESTION ACTION TYPES
export const GET_CODE_QUESTIONS = 'GET_CODE_QUESTIONS';
export const GET_CODE_QUESTION = 'GET_CODE_QUESTION';
export const ADD_CODE_QUESTION = 'ADD_CODE_QUESTION';
export const DELETE_CODE_QUESTION = 'DELETE_CODE_QUESTION';
export const UPDATE_CODE_QUESTION = 'UPDATE_CODE_QUESTION';
export const FILTER_CODE_QUESTIONS = 'FILTER_CODE_QUESTIONS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_CURRENT_CODE_QUESTION = 'SET_CURRENT_CODE_QUESTION';
export const CLEAR_CURRENT_CODE_QUESTION = 'CLEAR_CURRENT_CODE_QUESTION';
export const CODE_QUESTION_ERROR = 'CODE_QUESTION_ERROR';
export const RUN_CODE = 'RUN_CODE';
export const SUBMIT_CODE = 'SUBMIT_CODE';
export const RESET_CODE = 'RESET_CODE';
export const CODE_LOADING = 'CODE_LOADING';

// PRACTICE QUIZ ACTION TYPES
export const GET_PRACTICE_QUIZZES = 'GET_PRACTICE_QUIZZES';
export const GET_PRACTICE_QUIZ = 'GET_PRACTICE_QUIZ';
export const ADD_PRACTICE_QUIZ = 'ADD_PRACTICE_QUIZ';
export const DELETE_PRACTICE_QUIZ = 'DELETE_PRACTICE_QUIZ';
export const UPDATE_PRACTICE_QUIZ = 'UPDATE_PRACTICE_QUIZ';
export const FILTER_PRACTICE_QUIZZES = 'FILTER_PRACTICE_QUIZZES';
export const SET_CURRENT_PRACTICE_QUIZ = 'SET_CURRENT_PRACTICE_QUIZ';
export const PRACTICE_QUIZ_ERROR = 'PRACTICE_QUIZ_ERROR';

// QUIZ ACTION TYPES
export const GET_QUIZZES = 'GET_QUIZZES';
export const GET_QUIZ = 'GET_QUIZ';
export const ADD_QUIZ = 'ADD_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const FILTER_QUIZZES = 'FILTER_QUIZZES';
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ';
export const QUIZ_ERROR = 'QUIZ_ERROR';
